POST http://localhost:3000/api/registration HTTP/1.1
Content-Type: application/json

{"userName": "digvijay", "password":"12345684", "role" : "seller"}

#########

POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{"userName": "digvijay", "password": "12345684"}

#######

POST http://localhost:3000/api/addProduct HTTP/1.1
Content-Type: application/json

{ "userName": "digvijay", "productName": "apple", "price": 500, "description": "free buy" }

######

GET http://localhost:3000/api/listProducts HTTP/1.1


#####

POST http://localhost:3000/api/placeOrder HTTP/1.1
Content-Type: application/json

{ "productId" : "5eb54d6940b3418395ff945d", "customer": "avc"}


######


POST http://localhost:3000/api/getPurchaseList HTTP/1.1
Content-Type: application/json

{"userName": "abc"}


####

POST http://localhost:3000/api/changeOrderStatus HTTP/1.1
Content-Type: application/json

{"userName" : "digvijay", "purchaseId" : "5eb558a5dbe80a9788b4f637", "status" : "Accepted"}
